swagger: '2.0'
info:
  description: >-
    Welcome to OneMap API documentation.
  version: 1.0.0
  title: Onemap 2.0 API 
  termsOfService: 'https://www.onemap.sg/legal/termsofuse.html'
  contact:
    email: onemap@sla.gov.sg
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: developers.onemap.sg
basePath: /
tags:
  - name: OneMap 2.0 API documentation
    description: All about the OneMap API
    externalDocs:
      description: Find out more
      url: 'https://docs.onemap.sg'
schemes:
  - https
paths:


  # Authorization
  /privateapi/auth/post/getToken:
    post:
      tags:
        - Authentication Service (POST)
      summary: Retrieve token key
      description: 'This API authenticates the user credentials and the service returns response in JSON format.'
      operationId: getToken
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: email
          in: formData
          required: true
          type: string
          description: Registered email entered by the user during the registration.
        - name: password
          in: formData
          type: string
          required: true
          description: Registered password entered by the user during the registration. 
      responses:
        '200':
          description: Successful
        '403':
          description: Forbidden
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error


  # Search
  /commonapi/search:
    get:
      tags:
        - OneMap REST APIs
      summary: Provide searching of address data for a given search value.
      description: 'The API provides searching of address data for a given search value. It returns search results with both latitude, longitude and x, y coordinates of the searched.'
      operationId: search
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
      parameters:
        - name: searchVal
          in: query
          required: true
          type: string
          default: revenue
          description: Keywords entered by user that is used to filter out the results.
        - name: returnGeom
          in: query
          required: true
          type: string
          description: Checks if user wants to return the geometry.
          default: Y
        - name: getAddrDetails
          in: query
          required: true
          type: string
          description: Checks if user wants to return address details for a point.
          default: Y
        - name: pageNum
          in: query
          type: integer
          format: int64
          description: Specifies the page to retrieve your search results from.
          required: false
      responses:
        '200':
          description: Successful
        '403':
          description: Forbidden
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

      
  # Reverse Geocode (SVY21)
  /privateapi/commonsvc/revgeocodexy:     
    get:
      tags:
        - OneMap REST APIs
      summary: Retrieves a building address by specifying x, y coordinates
      description: 'The API retrieves a building address that lies within the defined buffer/radius of the specified x, y coordinates.'
      operationId: revgeocodexy
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: location
          in: query
          type: string
          description: X,Y Coordinates in SVY21 format
          default: 24291.97788882387,31373.0117224489
          required: true
        - name: token
          in: query
          type: string
          description: API token provided by the API token provided by the [Authentication Service](https://docs.onemap.sg/#authentication-service-post)
          default:
          required: true
        - name: buffer
          description: Rounds up all building in a circumference from a point like a compass; and searches building addresses within the buffer/radius range.
          required: false
          type: integer
          format: int64
          in: query
          default: 10
        - name: addressType
          description: Provide user the selection of All of HDB properties within the buffer/radius. If HDB is chosen, this will filter to show all HDB-related buildings.
          required: false
          type: string
          in: query
          default: All
        - name: otherFeatures
          required: false
          description: Enables users to retrieve information on resvoirs, playgrounds, jetties and many more.
          default: N
          type: string
          in: query

      responses:
        '200':
          description: Successful
        '403':
          description: Forbidden
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

  #Reverse Geocode(WGS84)
  /privateapi/commonsvc/revgeocode:     
    get:
      tags:
        - OneMap REST APIs
      summary: Retrieves a building address by specifying latitude, longitude coordinates
      description: 'This API retrieves a building address that lies within the defined buffer/radius of the specified latitude, longitude coordinates. Road names are retuned within 20m for the specified coordinates.'
      operationId: revgeocode
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: location
          in: query
          type: string
          description: Latitude and longitude Coodinates in WGS84 format.
          default: 1.3,103.8
          required: true
        - name: token
          in: query
          type: string
          description: API token provided by the API token provided by the [Authentication Service](https://docs.onemap.sg/#authentication-service-post)
          default:
          required: true
        - name: buffer
          description: Rounds up all building in a circumference from a point like a compass; and searches building addresses within the buffer/radius range.
          required: false
          type: integer
          format: int64
          in: query
          default: 10
        - name: addressType
          description: Provide user the selection of All of HDB properties within the buffer/radius. If HDB is chosen, this will filter to show all HDB-related buildings.
          required: false
          type: string
          in: query
          default: All
        - name: otherFeatures
          required: false
          description: Enables users to retrieve information on resvoirs, playgrounds, jetties and many more.
          default: N
          type: string
          in: query

      responses:
        '200':
          description: Successful
        '403':
          description: Forbidden
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error


  #4326 (WGS84) to 3857
  /commonapi/convert/4326to3857:     
    get:
      tags:
        - Coordinates Converter
      summary: This API provides 6 conversion functions between EPSG 3414 (SVY21), EPSG 3857 and EPSG 4326 (WGS84) formats.
      description: 'This API retrieves a building address that lies within the defined buffer/radius of the specified latitude, longitude coordinates. Road names are retuned within 20m for the specified coordinates.'
      operationId: 4326to3857
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: latitude
          in: query
          type: string
          description: Latitude Coordinates in WGS84 format.
          required: true
        - name: longitude
          in: query
          type: string
          description: Longitude Coordinates in WGS84 format.
          required: true

      responses:
        '200':
          description: Successful
        '403':
          description: Forbidden
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

#4326(WGS84) to 3414(SVY21)
  /commonapi/convert/4326to3414:     
    get:
      tags:
        - Coordinates Converter
      summary: This API provides 6 conversion functions between EPSG 3414 (SVY21), EPSG 3857 and EPSG 4326 (WGS84) formats.
      description: 'This API retrieves a building address that lies within the defined buffer/radius of the specified latitude, longitude coordinates. Road names are retuned within 20m for the specified coordinates.'
      operationId: 4326to3414
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: latitude
          in: query
          type: string
          description: Latitude Coordinates in WGS84 format.
          required: true
        - name: longitude
          in: query
          type: string
          description: Longitude Coordinates in WGS84 format.
          required: true

      responses:
        '200':
          description: Successful
        '403':
          description: Forbidden
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

#3414(SVY21) to 3857
  /commonapi/convert/3414to3857:     
    get:
      tags:
        - Coordinates Converter
      summary: This API provides 6 conversion functions between EPSG 3414 (SVY21), EPSG 3857 and EPSG 4326 (WGS84) formats.
      description: 'This API retrieves a building address that lies within the defined buffer/radius of the specified latitude, longitude coordinates. Road names are retuned within 20m for the specified coordinates.'
      operationId: 3414to3857
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: X
          in: query
          type: string
          description: X Coordinates in SVY21 format.
          required: true
        - name: Y
          in: query
          type: string
          description: Y Coordinates in SVY21 format.
          required: true

      responses:
        '200':
          description: Successful
        '403':
          description: Forbidden
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

#3414(SVY21) to 4326(WGS84)
  /commonapi/convert/3414to4326:     
    get:
      tags:
        - Coordinates Converter
      summary: This API provides 6 conversion functions between EPSG 3414 (SVY21), EPSG 3857 and EPSG 4326 (WGS84) formats.
      description: 'This API retrieves a building address that lies within the defined buffer/radius of the specified latitude, longitude coordinates. Road names are retuned within 20m for the specified coordinates.'
      operationId: 3414to4326
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: X
          in: query
          type: string
          description: X Coordinates in SVY21 format.
          required: true
        - name: Y
          in: query
          type: string
          description: Y Coordinates in SVY21 format.
          required: true

      responses:
        '200':
          description: Successful
        '403':
          description: Forbidden
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

#3857 to 3414(SVY21)
  /commonapi/convert/3857to3414:     
    get:
      tags:
        - Coordinates Converter
      summary: This API provides 6 conversion functions between EPSG 3414 (SVY21), EPSG 3857 and EPSG 4326 (WGS84) formats.
      description: 'This API retrieves a building address that lies within the defined buffer/radius of the specified latitude, longitude coordinates. Road names are retuned within 20m for the specified coordinates.'
      operationId: 3857to3414
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: X
          in: query
          type: string
          description: X Coordinates in SVY21 format.
          required: true
        - name: Y
          in: query
          type: string
          description: Y Coordinates in SVY21 format.
          required: true

      responses:
        '200':
          description: Successful
        '403':
          description: Forbidden
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

#3857 to 4326(WGS84)
  /commonapi/convert/3857to4326:     
    get:
      tags:
        - Coordinates Converter
      summary: This API provides 6 conversion functions between EPSG 3414 (SVY21), EPSG 3857 and EPSG 4326 (WGS84) formats.
      description: 'This API retrieves a building address that lies within the defined buffer/radius of the specified latitude, longitude coordinates. Road names are retuned within 20m for the specified coordinates.'
      operationId: 3857to4326
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: X
          in: query
          type: string
          description: X Coordinates in SVY21 format.
          required: true
        - name: Y
          in: query
          type: string
          description: Y Coordinates in SVY21 format.
          required: true

      responses:
        '200':
          description: Successful
        '403':
          description: Forbidden
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error


#Check Theme Status
  /privateapi/themesvc/checkThemeStatus:     
    get:
      tags:
        - Themes
      summary: Check Theme Status
      description: 'Check the updatedness of themes.'
      operationId: checkThemeStatus
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: queryName
          in: query
          type: string
          description: Queries status of a theme. Themes’ query names can be retrieved using [Get All Themes Info](https://docs.onemap.sg/#get-all-themes-info) service.
          default: 1.3,103.8
          required: true
        - name: dateTime
          description: |
            The date and time. Format **YYYY-MM-DDTHH:MM:SS:FFFZ**.
            EG: **2015-02-10T16:00:00.000Z**.
          required: true
          type: string
          format: date-time
          in: query
          default: 2015-02-10T16:00:00.000Z
        - name: token
          in: query
          type: string
          description: API token provided by the [Authentication Service](https://docs.onemap.sg/#authentication-service-post)
          required: true
      responses:
        '200':
          description: Successful
        '403':
          description: Forbidden
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

#Get Theme Info
  /privateapi/themesvc/getThemeInfo:     
    get:
      tags:
        - Themes
      summary: Get Theme Info
      description: 'This API searches themes via the queryName and returns the themes’ info.'
      operationId: getThemeInfo
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: token
          in: query
          type: string
          description: API token provided by the [Authentication Service](https://docs.onemap.sg/#authentication-service-post)
          required: true
        - name: queryName
          in: query
          type: string
          description: Queries status of a theme. Themes’ query names can be retrieved using [Get All Themes Info](https://docs.onemap.sg/#get-all-themes-info) service.
          default: 1.3,103.8
          required: true
      responses:
        '200':
          description: Successful
        '403':
          description: Forbidden
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

#Get All Themes Info
  /privateapi/themesvc/getAllThemesInfo:     
    get:
      tags:
        - Themes
      summary: Get All Themes Info
      description: 'This API retrieves and returns a list of all available themes.'
      operationId: getAllThemesInfo
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: token
          in: query
          type: string
          description: API token provided by the [Authentication Service](https://docs.onemap.sg/#authentication-service-post)
          required: true
        - name: moreInfo
          in: query
          type: string
          description: |
            **Default**: N
            **Values**: Y, N
            Returns more information of themes such as icon names, category names, and theme owners if set as Y.          
          default: N
          required: false
      responses:
        '200':
          description: Successful
        '403':
          description: Forbidden
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error





externalDocs:
  description: Find out more about OneMap
  url: 'https://docs.onemap.sg'
